### ISSUE TITLE
ARCH-COMP 2019

### ISSUE THREAD

**Issue by schillic** [JuliaReach/ReachabilityBenchmarks#93]
This is a meta issue for collecting tasks and cross-references for ARCH-COMP 2019.

### AFF
  * [x] add benchmark script to run all benchmarks (#94)
  * [x] adapt axis ranges in plots to suggestions in report (#118)
  * [x] double-check discrete-time time steps (#120)
  * [x] add dashed lines to plots for property (#118)
  * ISS
    * [x] add plot creation (#96)
    * [ ] resolve regression
  * Spacecraft rendezvous
    * [x] add benchmark script (#94)
    * [x] add plot creation (#94)
    * [x] investigate "*aborting*" scenario (no behavior after switching to the "*aborting*" location) (#103)
    * [x] update model to [recently proposed changes](https://cps-vo.org/node/49156#comment-1213) (#105)
    * [ ] make new versions work
    * [ ] investigate which specification is most efficient to check (`BadStatesProperty` or `SafeStatesProperty`, box given as constraints or as `BallInf`)
  * Powertrain
    * [x] add model (#41, #41, #112)
    * [ ] make it work
    * [ ] add script for benchmarking and plot creation
  * Building (#89)
    * [x] add plot creation (#95)
  * Platooning
    * [x] add benchmark script (#94)
    * [x] add plot creation (#94)
    * [x] add unbounded-time setting (#101)
    * [ ] make BND30 setting work
  * Gearbox
    * [ ] make it work (#86)
    * [ ] add script for benchmarking and plot creation

### NLN
  * [x] add benchmark script to run all benchmarks and create plots (#121)
  * [x] add TMJets to Reachability ([Reachability#537](https://github.com/JuliaReach/Reachability.jl/pull/537))
  * Van der Pol (#84)
    * [x] add scenario μ = 2 with evolution time = 8 seconds
    * [x] show both results in one plot (range of the plot: [-2.5,2.5]x[-4, 4])
  * Laub-Loomis (#83)
    * [x] add W=0.05 as an additional width
    * [x] show both results in one plot
    * [x] output width of x4 in the final set
  * Quadrotor (#97)
    * [x] update and add issue with bench results and plot (#98)
  * Spacecraft rendezvous (#59)
    * [x] add model (#122)
    * [ ] make it work

**Comment by schillic** [comment]
Current results:

### AFF

ISS
          ("ISU01", "dense") => TrialEstimate(1.103 s)
          ("ISS02", "discrete") => TrialEstimate(267.215 ms)
          ("ISU01", "discrete") => TrialEstimate(8.328 s)
          ("ISS01", "discrete") => TrialEstimate(1.906 s)
          ("ISU02", "discrete") => TrialEstimate(142.628 ms)
          ("ISS02", "dense") => TrialEstimate(515.296 ms)
          ("ISU02", "dense") => TrialEstimate(394.097 ms)
          ("ISS01", "dense") => TrialEstimate(2.625 s)


rendezvous
          ("SRNA01-SR01", "dense") => TrialEstimate(711.522 ms)
          ("SRNA01-SR01", "discrete") => TrialEstimate(339.373 ms)
          ("SRA01-SR02", "discrete") => TrialEstimate(550.754 ms)
          ("SRA01-SR02", "dense") => TrialEstimate(1.240 s)


building
          ("BLDF01-BDS01", "dense") => TrialEstimate(230.333 ms)
          ("BLDC01-BDS01", "dense") => TrialEstimate(157.276 ms)
          ("BLDF01-BDS01", "discrete") => TrialEstimate(136.422 ms)
          ("BLDC01-BDS01", "discrete") => TrialEstimate(133.928 ms)


platooning
          ("PLAD01_BND42", "discrete") => TrialEstimate(188.199 ms)
          ("PLAN01_UNB50", "discrete") => TrialEstimate(7.339 s)
          ("PLAD01_BND42", "dense") => TrialEstimate(600.418 ms)
          ("PLAN01_UNB50", "dense") => TrialEstimate(9.370 s)

**Comment by lbenet** [comment]
For NLN I think we should also add a point related to the Van der Pol system with a different parameter.

**Comment by schillic** [comment]
You can just edit above if you want.

**Comment by mforets** [comment]
> You can just edit above if you want.

I added the open task, thanks for the reminder Luis ;)
It has been communicated that we should experiment with different values of mu. This parameter governs non linearity and for increasing values the limit cycle becomes "sharper".
